# Generated by Django 4.2.7 on 2023-11-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='link',
            field=models.ManyToManyField(blank=True, to='bookmark.bookmark', verbose_name='Закладка'),
        ),
    ]
