# Generated by Django 4.2.7 on 2023-11-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='link',
            field=models.URLField(help_text='Ссылка', max_length=2000, verbose_name='Ссылка'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('author', 'link'), name='unique_link'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_collection'),
        ),
    ]
