# Generated by Django 4.2.7 on 2023-11-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_alter_bookmark_link_bookmark_unique_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='link',
            new_name='links',
        ),
    ]
