# Generated by Django 4.2.7 on 2023-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_rename_link_collection_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(help_text='Название коллекции закладок', max_length=150, verbose_name='Имя коллекции'),
        ),
    ]
