# Generated by Django 4.2.7 on 2023-11-16 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0004_alter_collection_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'default_related_name': 'collection', 'ordering': ('-created_at',), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bookmark author'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text='Bookmark description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.URLField(blank=True, editable=False, max_length=2000, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='link',
            field=models.URLField(help_text='Bookmark URL', max_length=2000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, editable=False, help_text='Bookmark', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='type',
            field=models.CharField(blank=True, editable=False, help_text='Bookmark type', max_length=150, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collection owner'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(help_text='Bookmarks collection description', max_length=500, verbose_name='Collection description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='links',
            field=models.ManyToManyField(blank=True, to='bookmark.bookmark', verbose_name='Bookmark'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(help_text='Bookmarks collection name', max_length=150, verbose_name='Collection name'),
        ),
    ]
