# Generated by Django 4.2.7 on 2023-11-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_alter_collection_options_alter_bookmark_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('created_at',), 'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
    ]
