# Generated by Django 4.2.7 on 2023-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='image',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
