# Generated by Django 4.2.7 on 2023-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_bookmark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, help_text='Описание закладки', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, editable=False, help_text='Название закладки', max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='type',
            field=models.CharField(blank=True, help_text='Тип закладки', max_length=150, verbose_name='Тип'),
        ),
    ]
