# Generated by Django 4.2.7 on 2023-11-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_alter_bookmark_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_link',
        ),
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_collection',
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('author', 'link'), name='unique_link', violation_error_message='You have this link already!'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('author', 'name'), name='unique_collection', violation_error_message='You have this collection already!'),
        ),
    ]
